# Force clean install and build - Dec 8 2025 v2
[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
cmds = ["rm -rf node_modules/.cache", "npm ci --force"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
