# Force clean install and build
[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci --force"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
